swagger: "2.0"
info:
  description: "The service exposes the APIs needed for car shopping"
  version: "1.0.0"
  title: "Car Shopping"
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
- name: "car shopping"
  description: "APIs car shopping"
schemes:
- "http"

paths:
  /carts:
    post:
      tags:
        - "cart"
      summary: "creates shopping cart having car"
      description: "creates shopping cart having car"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "create cart"
          schema:
            $ref: "#/definitions/cartmodel"
      responses: 
        "201":
          description: "resource cart created"
          schema:
            $ref: "#/definitions/cartmodel"
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error"
          
  /carts/{ID}:
    delete:
      tags:
        - "cart"
      summary: "delete cart"
      description: "delete cart"
      consumes:
      - "application/json"
      produces:
      - "application/json"  
      parameters:
        - in: "path"
          name: "ID"
          type: "string"
          required: true
      responses: 
        "201":
          description: "resource deleted"
          schema:
            $ref: "#/definitions/cartmodel"
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error"
          
    get:
      tags: 
      - "cart"
      summary: "return list of carts"
      description: "return list of carts"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "path"
          name: "ID"
          type: "string"
          required: true
          description: "Id to be filtered"
      responses:
        "200":
          description : "returns list of carts"
        "400":
           description : "Bad request"
        "404":
           description : "car not found"
           
    put:
      tags: 
      - "cart"
      summary: "add or remove cars from cart"
      description: "add or remove cars from cart"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
         - in: "body"
           name: "ID"
           schema:
            $ref: "#/definitions/cartmodel"
           required: true
          
      responses:
        "200":
          description : "add or remove cars from cart"
        "400":
           description : "Bad request"
        "404":
           description : "car not found"
        
  /cars/{ID}:
    get:
      tags: 
      - "car"
      summary: "return list of cars from warehouse"
      description: "return list of cars from warehouse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "path"
          name: "ID"
          type: "string"
          description: "Id to be filtered"
      responses:
        "200":
          description : "returns list of cars"
          schema:
            $ref: "#/definitions/carmodel"
        "400":
           description : "Bad request"
        "404":
           description : "car not found"
  

definitions:

  carmodel:
    type: "object"
    properties:
      location:
        type: "string"
      vehicles:
        type: "array"
        items:
          type: "object"
          properties:
            _id:
              type: "string"
            make:
              type: "string"
            model:
              type: "string"
            year_model:
              type: "string"
            price:
              type: "string"
            licensed:
              type: "string"
            date_added:
              type: "string"
        
  
  cartmodel:
    type: "object"
    properties:
      user:
        type: "string"
        description: "unique identifier"
      operation:
        type: "string"
        enum: [ADD,DELETE]
        description: "ADD for adding new car in cart. DELETE for deleting car from cart
      car:
          $ref: "#/definitions/carmodel"
          
  
